"""
Django settings for college_management_system project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import dj_database_url
import os
from pathlib import Path
from urllib.parse import urlparse

from college_management_system.database_url import resolve_render_postgres_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "f2zx8*lb*em*-*b+!&1lpp&$_9q9kmkar+l3x90do@s(+sr&x7",  # dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").strip().lower() == "true"

# -----------------------------------------------------------------------------
# Host / CSRF configuration
# -----------------------------------------------------------------------------
# We always allow localhost + Render's default subdomain so a deploy never 400s
# due to a misconfigured env var. Extra hosts can be added in two ways:
#   1. SITE_DOMAIN=example.com,www.example.com   (simple additive list)
#   2. ALLOWED_HOSTS=a,b,c                        (full override, power users)
#
# The CSRF_TRUSTED_ORIGINS list is derived automatically from the resolved
# ALLOWED_HOSTS (https:// is assumed, wildcard entries are handled). Any
# explicit CSRF_TRUSTED_ORIGINS env var is additive, not a replacement.

_default_hosts = ["127.0.0.1", "localhost", ".onrender.com"]
_site_domains = [h.strip() for h in os.environ.get("SITE_DOMAIN", "").split(",") if h.strip()]
_hosts_override = os.environ.get("ALLOWED_HOSTS", "").strip()

if _hosts_override:
    ALLOWED_HOSTS = [h.strip() for h in _hosts_override.split(",") if h.strip()]
    # Make sure the defaults are still present so health checks & Render subdomain never 400.
    for _h in _default_hosts:
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)
else:
    ALLOWED_HOSTS = list(_default_hosts) + _site_domains

# Render sets this to your *.onrender.com hostname; custom domains need SITE_DOMAIN.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)


def _origin_for(host: str) -> str:
    """Convert an ALLOWED_HOSTS entry into a CSRF-trusted https:// origin."""
    host = host.strip().lstrip("*")
    if host.startswith("."):
        # `.onrender.com` → `https://*.onrender.com`
        return f"https://*{host}"
    return f"https://{host}"


_csrf_env = [o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
_derived_csrf = [_origin_for(h) for h in ALLOWED_HOSTS if h not in ("127.0.0.1", "localhost")]

CSRF_TRUSTED_ORIGINS = []
for _origin in list(_csrf_env) + _derived_csrf:
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # My Apps
    'main_app.apps.MainAppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # Django 4.2+ has no django.middleware.timezone; per-request TZ is set here (Kenya).
    # Templates use django.template.context_processors.tz (not the old ".timezone" name).
    'main_app.middleware.ActivateKenyaTimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Third Part Middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # My Middleware
    'main_app.middleware.LoginCheckMiddleWare',
]

ROOT_URLCONF = 'college_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['main_app/templates'], #My App Templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main_app.context_processors.staff_role',
                'main_app.context_processors.operational_alerts',
                'main_app.context_processors.active_session_context',
                'main_app.context_processors.branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'college_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'django',
    #     'USER': os.environ.get('DB_USER'),
    #     'PASSWORD': os.environ.get('DB_PASS'),
    #     'HOST': '127.0.0.1',
    #     'PORT': '3307'
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
if not DEBUG:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization & time (ELEVATE DIGITAL HUB — Kenya, EAT / UTC+3)
# https://docs.djangoproject.com/en/4.2/topics/i18n/timezones/
#
# Datetimes are stored in UTC in the database (USE_TZ=True); the active
# timezone for each request is forced to Africa/Nairobi via middleware so
# all display, date-only filters, and naive form input are interpreted as
# Kenyan local time — never the hosting server's local clock.
LANGUAGE_CODE = 'en-gb'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_L10N = True
USE_TZ = True
FORMAT_MODULE_PATH = [
    'main_app.formats',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
AUTH_USER_MODEL = 'main_app.CustomUser'
AUTHENTICATION_BACKENDS = ['main_app.EmailBackend.EmailBackend']
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_mails")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = os.environ.get('EMAIL_ADDRESS') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "Elevate Digital Hub <admin@admin.com>"

# SMS / M-Pesa confirmations: wire to main_app.sms_placeholder.send_sms when ready (no-op for MVP).
# SMS_BACKEND = "dummy"
# Brand identity for ELEVATE DIGITAL HUB (single ICT training hub).
# COLLEGE_NAME / COLLEGE_LOCATION variable names are kept for backwards
# compatibility with existing template/view references; HUB_TAGLINE adds the
# ICT Hub System sub-line used on receipts, reports, and the login screen.
COLLEGE_NAME = os.environ.get("COLLEGE_NAME", "ELEVATE DIGITAL HUB")
COLLEGE_LOCATION = os.environ.get("COLLEGE_LOCATION", "")
HUB_TAGLINE = os.environ.get("HUB_TAGLINE", "ICT Hub System")

# Use non-manifest storage to avoid build failure on third-party CSS
# files that reference optional/missing assets.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Use DATABASE_URL when provided (Render/Heroku/etc). Falls back to the
# local SQLite config declared above when the env var isn't set.
# Optional DATABASE_EXTERNAL_URL overrides DATABASE_URL (use Render's
# External Database URL if the bare internal host dpg-…-a cannot resolve).
_database_url = os.environ.get("DATABASE_URL", "").strip()
_external_url = os.environ.get("DATABASE_EXTERNAL_URL", "").strip()
if _external_url:
    _database_url = _external_url
elif _database_url:
    _database_url = resolve_render_postgres_url(_database_url)
if _database_url:
    _pg_host = urlparse(_database_url).hostname or ""
    _render_internal_pg = _pg_host.startswith("dpg-") and "." not in _pg_host
    DATABASES['default'] = dj_database_url.parse(
        _database_url,
        conn_max_age=500,
        # Render internal Postgres (host dpg-…-a) is not reached over SSL.
        ssl_require=not DEBUG and not _render_internal_pg,
    )

# Behind Render/Heroku load balancers the original request is HTTPS; tell
# Django so secure cookies and redirects behave correctly.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

