# Generated by Django 4.2.29 on 2026-04-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_course_duration_unit_course_duration_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('reason', models.CharField(choices=[('admission', 'Admission confirmation'), ('payment', 'Payment confirmation'), ('class_reminder', 'Class reminder')], max_length=20)),
                ('status', models.CharField(choices=[('logged', 'Logged (not sent)'), ('sent', 'Sent'), ('failed', 'Failed')], default='logged', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='main_app.payment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='main_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
