# Generated by Django 4.2.29 on 2026-04-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_student_assigned_instructor_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual fee: full course amount, or per-month amount if MONTHLY.', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='fee_type',
            field=models.CharField(choices=[('FULL', 'FULL (one-time)'), ('MONTHLY', 'MONTHLY (per month × duration)')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee total locked at enrollment; course fee edits do not change this.', max_digits=10, null=True),
        ),
    ]
