# Generated by Django 4.2.29 on 2026-04-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_admin_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete: keep the record but hide from normal lists.'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff or admin who registered this student (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
