# Generated by Django 4.2.29 on 2026-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_staff_course_optional_non_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full name exactly as entered (single field; no reordering).', max_length=255),
        ),
    ]
