# Generated by Django 4.2.11 on 2026-04-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _table_columns(connection, table_name):
    try:
        with connection.cursor() as cursor:
            desc = connection.introspection.get_table_description(cursor, table_name)
        return {col.name for col in desc}
    except Exception:
        return set()


def _heal_missing_enrollment_schema(apps, schema_editor):
    """Create the `main_app_enrollment` table and `payment.enrollment_id` FK
    column if they are missing from the physical database.

    Migration 0015 declared these in Django's model state via
    SeparateDatabaseAndState(database_operations=[]), which skipped the actual
    CREATE TABLE / ADD COLUMN on the database. On production Postgres the
    table therefore never existed; any later migration that touches it (or
    runs a RunPython that queries it) fails with
    `relation "main_app_enrollment" does not exist`.

    This step is idempotent: on databases that already have the table/column
    (e.g. local SQLite where the ORM auto-created them), it's a no-op.
    """
    conn = schema_editor.connection
    existing_tables = set(conn.introspection.table_names())

    Enrollment = apps.get_model("main_app", "Enrollment")
    Payment = apps.get_model("main_app", "Payment")

    if Enrollment._meta.db_table not in existing_tables:
        schema_editor.create_model(Enrollment)

    payment_cols = _table_columns(conn, Payment._meta.db_table)
    if "enrollment_id" not in payment_cols:
        enrollment_field = Payment._meta.get_field("enrollment")
        schema_editor.add_field(Payment, enrollment_field)


def _noop_heal_reverse(apps, schema_editor):
    """No-op: we never want to drop the enrollment table on rollback here."""


def _copy_student_fields_to_enrollment(apps, schema_editor):
    """Carry soon-to-be-dropped Student fields onto matching Enrollment rows.

    Some fields were moved from Student to Enrollment as part of the
    multi-course refactor:
        Student.enrollment_level     -> Enrollment.enrollment_level
        Student.assigned_instructor  -> Enrollment.assigned_instructor
        Student.enrollment_total_fee -> Enrollment.total_fee

    This RunPython step preserves data on already-deployed databases. On a
    fresh/empty database it's a no-op. On SQLite (local), the legacy columns
    may not exist at all; we guard with a column-exists check so the
    migration is safe to re-run everywhere.
    """
    Student = apps.get_model("main_app", "Student")
    Enrollment = apps.get_model("main_app", "Enrollment")

    # Figure out which legacy columns actually exist on the student table.
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing_cols = {
            c.name for c in connection.introspection.get_table_description(
                cursor, Student._meta.db_table
            )
        }

    wanted = {
        "enrollment_level": "enrollment_level",
        "assigned_instructor_id": "assigned_instructor_id",
        "enrollment_total_fee": "total_fee",
    }
    present = {src: dst for src, dst in wanted.items() if src in existing_cols}
    if not present:
        return

    select_cols = ["id"] + list(present.keys())
    with connection.cursor() as cursor:
        cursor.execute(
            f'SELECT {", ".join(select_cols)} FROM {Student._meta.db_table}'
        )
        rows = cursor.fetchall()

    for row in rows:
        student_id = row[0]
        values = dict(zip(present.keys(), row[1:]))

        enrollments = Enrollment.objects.filter(student_id=student_id)
        if not enrollments.exists():
            continue
        update_kwargs = {}
        if "enrollment_level" in values and values["enrollment_level"]:
            update_kwargs["enrollment_level"] = values["enrollment_level"]
        if "assigned_instructor_id" in values and values["assigned_instructor_id"]:
            update_kwargs["assigned_instructor_id"] = values["assigned_instructor_id"]
        if "enrollment_total_fee" in values and values["enrollment_total_fee"]:
            # Only overwrite if the Enrollment doesn't already have a fee set.
            enrollments.filter(total_fee=0).update(total_fee=values["enrollment_total_fee"])
            update_kwargs.pop("enrollment_total_fee", None)

        if update_kwargs:
            enrollments.update(**update_kwargs)


def _noop_reverse(apps, schema_editor):
    """The forward op is idempotent; the reverse simply leaves Enrollment rows alone."""


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_integer_money_fields'),
    ]

    operations = [
        migrations.RunPython(_heal_missing_enrollment_schema, _noop_heal_reverse),
        migrations.RunPython(_copy_student_fields_to_enrollment, _noop_reverse),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assigned_instructor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_total_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full name as entered (single field). Used for display when set.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Teaching assignment: instructors should have a course; admission/finance may leave empty.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
