# Generated by Django — data fix for enrollment fees vs course full_fee

from django.db import migrations
from django.db.models import Sum


def forwards(apps, schema_editor):
    Enrollment = apps.get_model("main_app", "Enrollment")
    Payment = apps.get_model("main_app", "Payment")

    def legacy_total(course):
        payment_plan = getattr(course, "payment_plan", None) or "full"
        full_fee = int(course.full_fee or 0)
        monthly_fee = int(course.monthly_fee or 0)
        if payment_plan == "monthly":
            dv = int(course.duration_value or 0)
            du = getattr(course, "duration_unit", None) or "weeks"
            if dv <= 0:
                return monthly_fee
            if du == "months":
                months = dv
            else:
                months = max(1, (dv + 3) // 4)
            return months * monthly_fee
        return full_fee

    qs = Enrollment.objects.exclude(status="cancelled").select_related("course")
    for e in qs.iterator():
        if not e.course_id:
            continue
        c = e.course
        cur = int(e.total_fee or 0)
        full = int(c.full_fee or 0)
        paid = int(
            Payment.objects.filter(enrollment_id=e.pk).aggregate(t=Sum("amount"))["t"] or 0
        )
        target = max(full, paid)
        leg = legacy_total(c)
        if (cur == leg and target != cur) or (cur == 0 and full > 0 and target != cur):
            Enrollment.objects.filter(pk=e.pk).update(total_fee=target)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0024_director_role"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
