# Generated by Django 4.2.11 on 2026-05-08 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_retroactive_fee_whole_kes_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentFeeAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_fee', models.PositiveIntegerField()),
                ('new_fee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_fee_edits', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_audit_entries', to='main_app.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
