# Generated by Django 4.2.11 on 2026-05-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_enrollment_fee_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_kind', models.CharField(choices=[('bootcamp', 'Bootcamp'), ('workshop', 'Workshop'), ('talk', 'Tech talk'), ('hackathon', 'Hackathon'), ('other', 'Other community event')], default='workshop', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location_or_link', models.CharField(blank=True, default='', help_text='Room name, campus, or online meeting URL.', max_length=500)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Optional cap; leave empty for open attendance.', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='task_kind',
            field=models.CharField(choices=[('practical', 'Practical / lab'), ('homework', 'Homework / exercise'), ('project', 'Project'), ('capstone', 'Capstone / portfolio piece')], default='practical', help_text='Type of hands-on work (hub uses practicals & projects, not exam-heavy flows).', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='skills_track',
            field=models.CharField(blank=True, choices=[('', 'General ICT / mixed'), ('software_dev', 'Software Development'), ('web', 'Web Development'), ('graphic', 'Graphic Design'), ('cyber', 'Cybersecurity'), ('networking', 'Networking'), ('data', 'Data Analysis'), ('ai', 'AI & Prompt Engineering'), ('marketing', 'Digital Marketing'), ('video', 'Video Editing'), ('va', 'Virtual Assistant Skills'), ('freelance', 'Freelancing Skills')], default='', help_text='Primary digital skills lane for this programme (hub catalog).', max_length=24),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_on',
            field=models.DateField(blank=True, help_text='Date marked complete (certificate / cohort completion).', null=True),
        ),
        migrations.CreateModel(
            name='StudentHubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_url', models.URLField(blank=True, default='', max_length=500)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('upwork_url', models.URLField(blank=True, default='', max_length=500)),
                ('fiverr_url', models.URLField(blank=True, default='', max_length=500)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='hub/cv/')),
                ('skill_badges', models.CharField(blank=True, default='', help_text='Comma-separated skills e.g. HTML, Python, Canva.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_profile', to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='MentorNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes_authored', to='main_app.staff')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes', to='main_app.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main_app.hubevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_event_regs', to='main_app.student')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hubeventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='uniq_hub_event_student'),
        ),
    ]
