# Generated by Django 4.2.11 on 2026-05-11 09:37

from django.db import migrations, models
import django.utils.timezone


def forwards_renumber_admission(apps, schema_editor):
    """Assign EDH/YYYY/NNN to all learners; sync yearly counters."""
    Student = apps.get_model("main_app", "Student")
    AdmissionSequence = apps.get_model("main_app", "AdmissionSequence")
    from collections import defaultdict

    fallback_year = django.utils.timezone.now().year

    for row in Student.objects.all().iterator():
        Student.objects.filter(pk=row.pk).update(student_id=f"MIGTMP-{row.pk}")

    rows = list(Student.objects.all().order_by("enrollment_date", "pk"))
    by_year = defaultdict(list)
    for r in rows:
        y = r.enrollment_date.year if r.enrollment_date else fallback_year
        by_year[y].append(r)

    for year in sorted(by_year.keys()):
        chunk = by_year[year]
        for i, r in enumerate(chunk, start=1):
            Student.objects.filter(pk=r.pk).update(student_id=f"EDH/{year}/{i:03d}")
        AdmissionSequence.objects.update_or_create(
            year=year,
            defaults={"last_value": len(chunk)},
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_hub_skills_events_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0, help_text='Last sequence used for this year.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission sequence',
                'verbose_name_plural': 'Admission sequences',
                'ordering': ('-year',),
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Official admission number (EDH/YYYY/NNN). Assigned automatically; do not edit manually.', max_length=24, unique=True),
        ),
        migrations.RunPython(forwards_renumber_admission, backwards_noop),
    ]
