# Generated by Django 4.2.11 on 2026-05-11 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _backfill_audit_rows(apps, schema_editor):
    AuditLog = apps.get_model("main_app", "AuditLog")
    Student = apps.get_model("main_app", "Student")
    for row in AuditLog.objects.all().iterator():
        ev = (row.legacy_event or "").strip()
        activity = (row.activity or "").strip()
        module = (row.module or "").strip()
        audit_action = row.audit_action or "other"
        new_activity = activity
        new_module = module
        new_action = audit_action
        target = (row.target_record or "").strip()

        if ev and not activity:
            new_activity = ev.replace("_", " ").title()[:255]
        if not module:
            el = ev.lower()
            if "payment" in el:
                new_module = "Fees & Payments"
                new_action = "create"
            elif "enrollment" in el:
                new_module = "Enrollment"
                new_action = "create"
            elif "student_registered" in el or (
                "student" in el and "registered" in el
            ):
                new_module = "Students"
                new_action = "create"
            elif "fee" in el:
                new_module = "Fees & Payments"
                new_action = "update"

        if row.student_id and not target:
            try:
                st = Student.objects.only("student_id").get(pk=row.student_id)
                sid = (st.student_id or "").strip() or f"id-{row.student_id}"
                target = f"Student: {sid}"[:512]
            except Exception:
                pass

        upd = []
        if new_activity != activity:
            row.activity = new_activity
            upd.append("activity")
        if new_module and new_module != module:
            row.module = new_module
            upd.append("module")
        if new_action != audit_action:
            row.audit_action = new_action
            upd.append("audit_action")
        if target and target != (row.target_record or "").strip():
            row.target_record = target
            upd.append("target_record")
        if upd:
            row.save(update_fields=upd)


def _backfill_audit_rows_safe(apps, schema_editor):
    try:
        _backfill_audit_rows(apps, schema_editor)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_admission_edh_numbers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="action",
            new_name="legacy_event",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="activity",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("export", "Export"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="module",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_record",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_role",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="main_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(_backfill_audit_rows_safe, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["module", "-created_at"], name="main_app_au_module_37b3cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["audit_action", "-created_at"],
                name="main_app_au_audit_a_909eff_idx",
            ),
        ),
    ]
