# Generated by Django 4.2.11 on 2026-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_submission_coursework_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionattachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
